FROM ubuntu:20.04

RUN apt-get -y update && DEBIAN_FRONTEND=noninteractive apt-get -y install \
    git \
    wget \
    cmake \
    python3 \
    python3-pip \
    build-essential \
	  ninja-build \
	  curl \
	  mesa-common-dev \
	  libglu1-mesa-dev \
	  libglib2.0-0 \
    fontconfig \
    libxcb-* \
    libxkbcommon-x11-0 \
    libegl-dev \
    libcups2

RUN pip3 install aqtinstall

ARG QT=5.15.2
ARG QT_MODULES=
ARG QT_HOST=linux
ARG QT_TARGET=desktop
ARG QT_ARCH=gcc_64
RUN aqt install --outputdir /opt/qt ${QT} ${QT_HOST} ${QT_TARGET} ${QT_ARCH} -m ${QT_MODULES}

ENV PATH /opt/qt/${QT}/${QT_ARCH}/bin:$PATH
ENV QT_PLUGIN_PATH /opt/qt/${QT}/${QT_ARCH}/plugins/
ENV QML_IMPORT_PATH /opt/qt/${QT}/${QT_ARCH}/qml/
ENV QML2_IMPORT_PATH /opt/qt/${QT}/${QT_ARCH}/qml/
ENV CMAKE_PREFIX_PATH /opt/qt/${QT}/${QT_ARCH}/lib/cmake/Qt5
